### ISSUE TITLE
Reload : Fix defunct

### ISSUE THREAD

**Issue by Benoit-Forveille** [naemon/naemon-core#150] opened 2016-09-25 16:30 UTC
Hi,

After several reload, there are many defunct process.
in daemon-init, change the reload function

reload() {
    echo -n "Reloading $prog: "
    # pkill -HUP -u ${user} -f ${exec}
    kill -HUP $PID
    retval=$?
    echo
}

**Comment by hurr1c4n** [comment] 2016-10-10 17:23
Hi,

with my naemon environment I have the same issue.
I solve it by adding the parameter -o.

"-o, --oldest
              Select only the oldest (least recently started) of the matching processes.
"
With this option, I reload the process leader only.

```
reload() {
    log_daemon_msg "Reloading $prog: "
    retval=0
#    pkill -HUP -u ${user} -f ${exec}
    pkill -HUP -u ${user} -f ${exec} -o
    retval=$?
    log_end_msg $retval
}
```

**Comment by ioguix** [comment] 2016-10-14 07:45
Hi,

We had the same issue here. After moving from Nagios et Naemon (lot of conf to review, lot of reload), we had 363 naemon defuncts processes.

We applied this fix yesterday, restarted Naemon, had a few reload since then, but no more than on defunct at a time according to the monitoring.

**Comment by dirtyren** [comment] 2017-12-22 15:49
I did this small improvement for my installation.
  In case the pid file does't exist for some reason, it does the old reload and when it reloads, it recreates the PID file, so the new kill -HUP will work on the next reload.

   if [ -e  $pidfile ]; then
        PID=`cat $pidfile`;
        kill -HUP $PID >/dev/null 2>/dev/null
    else
        pkill -HUP -u ${opmon_user} -f ${opmon_bin}
    fi

**Comment by sciolto** [comment] 2018-03-08 16:01
naemon 1.0.6 on CentOS 6.9, same issue. 

Fixed with @hurr1c4n 's patch 

Thank you !

**Comment by sni** [comment] 2018-03-08 17:57
does anyone want to put that into a pull request?

**Comment by dirtyren** [comment] 2018-03-10 00:39
Pull request #216.

**Comment by jacobbaungard** [comment] 2018-05-31 14:48
Merged (https://github.com/naemon/naemon-core/commit/893d1df40dc4c5649765e26c0edd2f30af7e9b87)

**Closed by jacobbaungard** 2018-05-31 14:48 UTC

**Comment by pvdputte** [comment] 2018-08-20 10:41
FYI, I think that this fix is not present in the 1.0.7 and 1.0.8 packages.

**Comment by jacobbaungard** [comment] 2018-08-20 11:10
I just tested on CentOS 6 (installed from [here](https://labs.consol.de/naemon/release/v1.0.8/rhel6/x86_64/)) and it looks like the patch is included correctly. Which packages did you try?

I guess the change only applies to systems that doesn't use systemd.

```
[root@living-mollusk ~]# cat /etc/init.d/naemon 
...
reload() {
    echo -n "Reloading $prog: "
    if [ -e $pidfile ]; then
        PID=`cat $pidfile`;
        kill -HUP $PID >/dev/null 2>/dev/null
    else
        pkill -HUP -u ${user} -f ${exec}
    fi
    retval=$?
    echo
}
...
```

**Comment by pvdputte** [comment] 2018-08-20 11:49
I'm on Debian 9 stretch. It's a test VM installed from scratch last weekend.

```
$ cat /etc/debian_version 
9.5

$ grep -A6 -e "^reload()" /etc/init.d/naemon 
reload() {
    log_daemon_msg "Reloading $prog: "
    retval=0
    pkill -HUP -u ${user} -f ${exec}
    retval=$?
    log_end_msg $retval
}

$ dpkg -S naemon|grep /etc/init.d/naemon
naemon-core: /etc/init.d/naemon

$ dpkg -l | grep naemon-core
ii  naemon-core                          1.0.8                          amd64        host/service/network monitoring and management system

$ apt-cache show naemon-core
Package: naemon-core
Priority: optional
Section: net
Installed-Size: 204
Maintainer: Naemon Core Development Team <naemon-dev@monitoring-lists.org>
Architecture: amd64
Version: 1.0.8
Depends: adduser, coreutils (>= 4.5.3), lsb-base (>= 3.0-6), bsd-mailx | mailx | sendemail, libc6 (>= 2.4), libglib2.0-0 (>= 2.12.0), libnaemon
Recommends: nagios-plugins
Filename: dists/stretch/main/binary-amd64/naemon-core_1.0.8.debian9.amd64.deb
Size: 42242
MD5sum: e869a2d0babc6c068d1dd8f7323e8e63

$ cat /etc/apt/sources.list.d/labs-consol-stable.list 
deb http://labs.consol.de/repo/stable/debian stretch main
```
Starting from a clean system to rule out any config management task interference I may be forgetting about:

```
# grep -A6 ^reload /etc/init.d/naemon
grep: /etc/init.d/naemon: No such file or directory

# apt-get clean
# apt-get update
# apt-get install naemon-core
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  naemon-core
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 42.2 kB of archives.
After this operation, 209 kB of additional disk space will be used.
Get:1 http://labs.consol.de/repo/stable/debian stretch/main amd64 naemon-core amd64 1.0.8 [42.2 kB]
Fetched 42.2 kB in 0s (383 kB/s) 
Selecting previously unselected package naemon-core.
(Reading database ... 42605 files and directories currently installed.)
Preparing to unpack .../naemon-core_1.0.8_amd64.deb ...
Unpacking naemon-core (1.0.8) ...
Setting up naemon-core (1.0.8) ...
Processing triggers for systemd (232-25+deb9u4) ...
Processing triggers for man-db (2.7.6.1-2) ...

# grep -A6 ^reload /etc/init.d/naemon
reload() {
    log_daemon_msg "Reloading $prog: "
    retval=0
    pkill -HUP -u ${user} -f ${exec}
    retval=$?
    log_end_msg $retval
}
```

**Comment by jacobbaungard** [comment] 2018-08-20 12:27
Strange. I have confirmed that on Debian Stretch as well. @sni could you take a look at this?

Thanks for the report @pvdputte

**Comment by sni** [comment] 2018-08-26 17:19
debian and ubuntu packaging are using a complete differen rc script from here: https://github.com/naemon/naemon-core/blob/master/debian/naemon-core.naemon.init

Feel free to send pull requests for that one as well.
