### ISSUE TITLE
Improve tests for macros

### ISSUE THREAD

**Issue by pengi** [naemon/naemon-core#56] opened 2014-03-31 14:39 UTC
The macro library needs a total rewrite sooner or later. The mkstr isn't really thread safe (with static variables in the method to temporary store variables), and it isn't that performance efficient to resolve an array of all possible macros, if some are quite performance heavy (listing groups, counting services, counting rocks in the entire beach, and so).

To be able to rewrite the macro library, we first need to improve the test suite.

So each macro should be a part of at least one test that extracts unique information of a mocked object.

Some tests is already available in the macro test suite. Create another test suite just to test the different macros, not the explicit escaping, is preffered.

**Comment by catharsis** [comment] 2016-05-06 08:33
I'm closing this since it has stagnated. While more tests would be nice, I don't think it makes sense to track the issue of writing them separately. I'd rather we build a suite of regression tests if/when we get around to giving the macro subsystem its much-needed overhaul.

**Closed by catharsis** 2016-05-06 08:33 UTC
Labels: enhancement
