### ISSUE TITLE
reloading leaves zombies processes

### ISSUE THREAD

**Issue by rottenbytes** [naemon/naemon-core#116] opened 2015-06-22 10:23 UTC
Hi,

I noticed that reloading naemon (via the init script) leaves zombies hanging out, which seem to be the running checks at the moment of the reload. Using restart does not have this effect. 

I was unable to find my way through the source code to where it happens, so no PR, sorry :disappointed:

**Comment by catharsis** [comment] 2016-02-26 08:44
I'm not able to reproduce this since merging #125, at least - we've done quite a bit of changes to the init script and internal child handling. I'm closing this, but feel free to reopen with more information.

**Closed by catharsis** 2016-02-26 08:44 UTC
