### ISSUE TITLE
OK notification sent during scheduled downtime

### ISSUE THREAD

**Issue by canehan** [naemon/naemon-core#297] opened 2019-07-11 15:33 UTC
If a service enters a scheduled downtime while being in WARNING and it's states comes back to OK, a SERVICE NOTIFICATION will be sent regardless of the downtime.

I think that no notification should be emitted during downtime as [stated in documentation](https://www.naemon.org/documentation/usersguide/downtime.html#how_scheduled_downtime_affects_notifications).

See attached log file for a trace of this behaviour:
1. put service "Service status" in warning
2. start downtime
3. show that new warning notification is blocked
4. put service in OK state
5. notification is sent

Behaviour as been seen in production and with a test system: basic configuration with all notifications allowed, flapping detection disabled during test.

Software versions are installed through RPM on a CentOS Linux release 7.5.1804 (Core) system :
- thruk-2.30-3.x86_64
- naemon-1.0.8-0.noarch.

Is there some configuration option that I missed ?

**Comment by nook24** [comment] 2019-07-15 15:47
That's not a bug.

> If a service enters a scheduled downtime while being in WARNING and it's states comes back to OK, a SERVICE NOTIFICATION will be sent regardless of the downtime.

In the example you pasted, your service send a notification (Warning) **before** the scheduled downtime started:
```
[1562857303] SERVICE NOTIFICATION: Xavier Canehan;testserver;Service status;WARNING;service-notification-grouper;initial status is warning
[1562857335] EXTERNAL COMMAND: SCHEDULE_SVC_DOWNTIME;testserver;Service status;1562857260;1562864460;1;0;7200;Canehan Xavier;no notification should occur from now

[1562857335] SERVICE DOWNTIME ALERT: testserver;Service status;STARTED; Service has entered a period of scheduled downtime
```

If the system send you a Non-Ok notification before a downtime started, you will also get the recovery notification even if the recovery event happens in the downtime.

If a service did **not** send you a notification before the scheduled downtime, you will also not receive any notifications while the service is in a scheduled downtime.

**Comment by sni** [comment] 2019-07-15 15:49
I'd say this is a bug. No matter what, but if something is in a scheduled downtime, i don't want to get any notification.

**Comment by nook24** [comment] 2019-07-15 15:53
If you want to filter those notifications you can pass [$HOSTDOWNTIME$](https://www.naemon.org/documentation/usersguide/macrolist.html#hostdowntime) and [$SERVICEDOWNTIME$](https://www.naemon.org/documentation/usersguide/macrolist.html#servicedowntime) to your notification commands...

> I'd say this is a bug. No matter what, but if something is in a scheduled downtime, i don't want to get any notification.

AFIK this is the default behavior since Nagios 3. So if this get's changed, please make it configurable.

Also (at least in my case) my Naemon opens a Ticket for issues and also close the ticket automatically in case of a recovery. 
This would get smashed up.

**Comment by sni** [comment] 2019-07-16 12:59
alright, since this has always been the case and people rely on it, we should update the documentation accordingly.

**Comment by sni** [comment] 2019-07-16 13:08
see https://github.com/naemon/naemon.github.io/pull/96

**Comment by sni** [comment] 2019-07-16 13:15
closing this, since it works as expected. We just updated the documentation.

**Closed by sni** 2019-07-16 13:15 UTC
