### ISSUE TITLE
nameon 104 crash after logrotate

### ISSUE THREAD

**Issue by GerasDraugas** [naemon/naemon-core#139] opened 2016-06-08 07:23 UTC
Aflter logrotate: `/usr/sbin/logrotate -f /etc/logrotate.d/naemon-core`

```
/var/log/naemon/naemon.log {
    daily
    rotate 3650
    nocompress
    olddir archives
    dateext
    dateformat -%Y%m%d
    missingok
    notifempty
    postrotate
      localstatedir=/var/lib/naemon
      [ -f /var/run/naemon/naemon.pid ] && kill -s USR1 `cat /var/run/naemon/naemon.pid`
    endscript
    create 0664 naemon naemon
}
```
log:
```
[2016-06-08 07:02:18] Event broker module '/usr/lib64/naemon/naemon-livestatus/livestatus.so' deinitialized successfully.
[2016-06-08 07:02:18] livestatus: deinitializing
[2016-06-08 07:02:18] Event broker module 'NERD' deinitialized successfully.
[2016-06-08 07:02:18] Error: Polling for input on 0x1b80130 failed: Interrupted system call
```

**Comment by catharsis** [comment] 2016-06-08 07:30
Thanks for the report! This is most likely a duplicate of #138, which is fixed in `master`. Feel free to build from source and verify that this is the case - otherwise we'll try to make a new release available that includes the fix for #138 as soon as time allows. I'm closing this issue in the meantime.

**Closed by catharsis** 2016-06-08 07:30 UTC
